# Generated by Django 4.2.16 on 2026-07-31 02:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("company", models.CharField(max_length=128)),
                ("phone", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "admin_contacts",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("panel", models.CharField(default="india", max_length=16)),
                ("origin_city", models.CharField(max_length=64)),
                (
                    "origin_state",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("destination_city", models.CharField(max_length=64)),
                (
                    "destination_state",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("transport_mode", models.CharField(default="road", max_length=32)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("origin_lat", models.FloatField(blank=True, null=True)),
                ("origin_lng", models.FloatField(blank=True, null=True)),
                ("destination_lat", models.FloatField(blank=True, null=True)),
                ("destination_lng", models.FloatField(blank=True, null=True)),
                ("carrier_id", models.CharField(blank=True, default="", max_length=32)),
                (
                    "carrier_company",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("cargo_type", models.CharField(default="General", max_length=64)),
                ("distance_km", models.FloatField(default=0)),
                ("distance_covered_km", models.FloatField(default=0)),
                ("distance_remaining_km", models.FloatField(default=0)),
                ("progress", models.FloatField(default=0)),
                ("planned_transit_hours", models.FloatField(default=24)),
                ("eta_hours", models.FloatField(default=24)),
                ("speed_kmh", models.FloatField(default=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_transit", "In Transit"),
                            ("delayed", "Delayed"),
                            ("at_warehouse", "At Warehouse"),
                            ("customs_hold", "Customs Hold"),
                            ("loading", "Loading"),
                            ("at_port", "At Port"),
                            ("rerouted", "Rerouted"),
                            ("delivered", "Delivered"),
                        ],
                        default="in_transit",
                        max_length=32,
                    ),
                ),
                ("is_delayed", models.BooleanField(default=False)),
                ("delay_hours_current", models.FloatField(default=0)),
                ("delay_duration_minutes", models.FloatField(default=0)),
                (
                    "delay_severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=16,
                    ),
                ),
                ("disruption_type", models.CharField(default="none", max_length=64)),
                ("disruption_flag", models.SmallIntegerField(default=0)),
                ("risk_score", models.FloatField(default=20)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=16,
                    ),
                ),
                ("is_anomaly", models.BooleanField(default=False)),
                ("delay_probability", models.FloatField(default=0)),
                ("cascade_risk_score", models.FloatField(default=0)),
                ("road_closure_flag", models.SmallIntegerField(default=0)),
                ("strike_event_flag", models.SmallIntegerField(default=0)),
                ("traffic_incident_flag", models.SmallIntegerField(default=0)),
                ("customs_hold_flag", models.SmallIntegerField(default=0)),
                ("holiday_flag", models.SmallIntegerField(default=0)),
                ("maintenance_flag", models.SmallIntegerField(default=0)),
                ("temp_breach_flag", models.SmallIntegerField(default=0)),
                ("border_crossing_flag", models.SmallIntegerField(default=0)),
                ("night_driving_flag", models.SmallIntegerField(default=0)),
                ("vehicle_breakdown_flag", models.SmallIntegerField(default=0)),
                ("accident_reported_flag", models.SmallIntegerField(default=0)),
                ("alt_route_needed", models.BooleanField(default=False)),
                ("alternate_routes_avail", models.SmallIntegerField(default=0)),
                ("weather_code", models.CharField(default="clear", max_length=32)),
                ("weather_condition", models.TextField(blank=True, default="")),
                ("wind_speed_kmh", models.FloatField(default=10)),
                ("visibility_km", models.FloatField(default=10)),
                ("live_weather", models.JSONField(blank=True, default=dict)),
                ("segment_congestion_idx", models.FloatField(default=0)),
                ("port_congestion_idx", models.FloatField(default=0)),
                (
                    "traffic_congestion_level",
                    models.CharField(default="Low", max_length=16),
                ),
                ("vehicle_type", models.CharField(default="Tata 407", max_length=64)),
                ("vehicle_age_years", models.FloatField(default=3)),
                ("driver_experience_years", models.FloatField(default=5)),
                ("driver_rest_hours_prior", models.FloatField(default=8)),
                ("num_toll_plazas", models.IntegerField(default=0)),
                ("num_state_border_crossings", models.IntegerField(default=0)),
                ("eway_bill_verified", models.SmallIntegerField(default=1)),
                ("gps_route_deviation_km", models.FloatField(default=0)),
                ("checkpoint_delay_minutes", models.FloatField(default=0)),
                ("origin_wh_congestion_pct", models.FloatField(default=40)),
                ("dest_wh_congestion_pct", models.FloatField(default=30)),
                ("upstream_shipment_delay_minutes", models.FloatField(default=0)),
                ("order_type", models.CharField(default="B2B", max_length=16)),
                (
                    "priority_level",
                    models.CharField(default="Scheduled-Freight", max_length=32),
                ),
                ("is_monsoon_season", models.SmallIntegerField(default=0)),
                ("is_festival_season", models.SmallIntegerField(default=0)),
                ("fuel_price_per_litre", models.FloatField(default=104)),
                ("shipment_value_inr", models.FloatField(default=100000)),
                ("value_usd", models.IntegerField(default=1200)),
                ("route_avg_delay_7d", models.FloatField(default=0)),
                ("route_disruption_cnt_30d", models.IntegerField(default=0)),
                ("carrier_on_time_rate", models.FloatField(default=0.8)),
                ("seasonal_risk_score", models.FloatField(default=0.3)),
                ("same_lane_delay_ratio", models.FloatField(default=0.3)),
                ("top_risk_factors", models.JSONField(blank=True, default=list)),
                ("reroute_options", models.JSONField(blank=True, default=list)),
                (
                    "recommended_action",
                    models.CharField(default="no_action", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "shipments",
                "ordering": ["-risk_score"],
                "indexes": [
                    models.Index(fields=["status"], name="shipments_status_cda325_idx"),
                    models.Index(
                        fields=["-risk_score"], name="shipments_risk_sc_afa272_idx"
                    ),
                    models.Index(
                        fields=["risk_level"], name="shipments_risk_le_49eb04_idx"
                    ),
                    models.Index(fields=["panel"], name="shipments_panel_245c75_idx"),
                    models.Index(
                        fields=["origin_city"], name="shipments_origin__a41d2e_idx"
                    ),
                    models.Index(
                        fields=["destination_city"], name="shipments_destina_c9c480_idx"
                    ),
                    models.Index(
                        fields=["carrier_id"], name="shipments_carrier_66afd1_idx"
                    ),
                    models.Index(
                        fields=["-last_updated"], name="shipments_last_up_d70d12_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RefreshLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refresh_type",
                    models.CharField(
                        choices=[
                            ("weather", "Weather Refresh"),
                            ("shipments", "Shipment Sync"),
                            ("alerts", "Alert Sync"),
                        ],
                        default="weather",
                        max_length=32,
                    ),
                ),
                ("cities_refreshed", models.IntegerField(default=0)),
                ("shipments_updated", models.IntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("refreshed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "refresh_log",
                "ordering": ["-refreshed_at"],
                "indexes": [
                    models.Index(
                        fields=["-refreshed_at"], name="refresh_log_refresh_f2d82b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DemoRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=256)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("company", models.CharField(blank=True, default="", max_length=256)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Shipper", "Shipper (Manufacturer/Retailer)"),
                            ("Carrier", "Carrier (Truckload/Ocean Line)"),
                            ("LSP", "LSP (3PL/Freight Forwarder)"),
                        ],
                        default="Shipper",
                        max_length=64,
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        choices=[
                            ("< 500", "Less than 500 loads"),
                            ("500 - 5000", "500 - 5,000 loads"),
                            ("> 5000", "More than 5,000 loads"),
                        ],
                        default="< 500",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("converted", "Converted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "demo_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="demo_reques_email_b31391_idx"),
                    models.Index(
                        fields=["status"], name="demo_reques_status_965d0c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CascadeEvent",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                (
                    "trigger_city",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "trigger_reason",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("total_affected_nodes", models.IntegerField(default=0)),
                ("total_affected_shipments", models.IntegerField(default=0)),
                ("total_financial_impact_inr", models.BigIntegerField(default=0)),
                ("estimated_recovery_hours", models.FloatField(default=0)),
                ("cascade_nodes", models.JSONField(blank=True, default=list)),
                ("recovery_plan", models.JSONField(blank=True, default=dict)),
                ("propagation_graph", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cascade_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="cascade_eve_created_4de91d_idx"
                    ),
                    models.Index(
                        fields=["trigger_city"], name="cascade_eve_trigger_66f39b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.RegexValidator(
                                message="Username may only contain lowercase letters, digits, underscores, and dots.",
                                regex="^[a-z0-9_\\.]+$",
                            ),
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        help_text="bcrypt $2b$ hash — never store plaintext",
                        max_length=256,
                        validators=[django.core.validators.MinLengthValidator(60)],
                    ),
                ),
                (
                    "panel",
                    models.CharField(
                        choices=[
                            ("india", "India Panel"),
                            ("customer", "Customer Panel"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("operator", "Operator"),
                            ("admin", "Admin"),
                            ("customer", "Customer"),
                        ],
                        default="customer",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_users",
                        to="api.admincontact",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "indexes": [
                    models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
                    models.Index(fields=["panel"], name="users_panel_dc537f_idx"),
                    models.Index(fields=["email"], name="users_email_4b85f2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("panel", models.CharField(default="india", max_length=16)),
                ("type", models.CharField(blank=True, default="", max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("risk_score", models.FloatField(default=0)),
                ("delay_probability", models.FloatField(default=0)),
                ("cascade_risk", models.FloatField(default=0)),
                ("top_risk_factors", models.JSONField(blank=True, default=list)),
                ("reroute_options", models.JSONField(blank=True, default=list)),
                ("weather_warning", models.BooleanField(default=False)),
                (
                    "weather_icon",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                (
                    "weather_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="api.shipment",
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="alerts_created_6327ec_idx"
                    ),
                    models.Index(fields=["severity"], name="alerts_severit_362484_idx"),
                    models.Index(fields=["panel"], name="alerts_panel_459de3_idx"),
                ],
            },
        ),
    ]
