# Generated by Django 4.2.16 on 2026-08-06 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_supportticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.RegexValidator(
                                message="Username may only contain lowercase letters, digits, underscores, and dots.",
                                regex="^[a-z0-9_\\.]+$",
                            ),
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        help_text="bcrypt $2b$ hash — never store plaintext",
                        max_length=256,
                        validators=[django.core.validators.MinLengthValidator(60)],
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "admin_users",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.RegexValidator(
                                message="Username may only contain lowercase letters, digits, underscores, and dots.",
                                regex="^[a-z0-9_\\.]+$",
                            ),
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        help_text="bcrypt $2b$ hash — never store plaintext",
                        max_length=256,
                        validators=[django.core.validators.MinLengthValidator(60)],
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "admin_contact_name",
                    models.CharField(blank=True, default="Jani Ops", max_length=128),
                ),
                (
                    "admin_contact_email",
                    models.CharField(
                        blank=True, default="ops.india@logisense.in", max_length=256
                    ),
                ),
                (
                    "admin_contact_phone",
                    models.CharField(
                        blank=True, default="+91 98982 13090", max_length=32
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "customers",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="admin_contact",
        ),
        migrations.AlterField(
            model_name="demorequest",
            name="volume",
            field=models.CharField(
                choices=[
                    ("< 500", "Less than 500 loads"),
                    ("500 - 5000", "500 – 5,000 loads"),
                    ("> 5000", "More than 5,000 loads"),
                ],
                default="< 500",
                max_length=32,
            ),
        ),
        migrations.DeleteModel(
            name="AdminContact",
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["username"], name="customers_usernam_fad06d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="customers_email_92e882_idx"),
        ),
        migrations.AddIndex(
            model_name="adminuser",
            index=models.Index(
                fields=["username"], name="admin_users_usernam_8a6e5b_idx"
            ),
        ),
        # Clear all existing support tickets before changing the FK target.
        # Old tickets reference the old 'users' table which is being dropped.
        migrations.RunSQL(
            sql="DELETE FROM support_ticket;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_tickets",
                to="api.customer",
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
