# Generated by Django 4.2.16 on 2026-08-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clean_auth_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='subject_type',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
    ]
